name: fuga

on:
  push:
    branches:
      - feature/fuga
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: npm install
    - name: build storybook
      run: npm run build-storybook
    - name: deploy storybook
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: storybook-static
                        


